# Generated by Django 4.2.1 on 2023-05-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('benificary_name', models.CharField(max_length=500, unique=True)),
                ('benificary_description', models.TextField(blank=True, null=True)),
                ('idBe', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_name', models.CharField(choices=[('College of Agriculture', 'College of Agriculture'), ('College of Arts and Sciences', 'College of Arts and Sciences'), ('College of Computer Studies', 'College of Computer Studies'), ('College of Engineering', 'College of Engineering'), ('College of Nursing', 'College of Nursing'), ('School of Business and Management', 'School of Business and Management'), ('School of Education', 'School of Education'), ('Professional Schools', 'Professional Schools')], max_length=50)),
                ('idCol', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('coor_first_name', models.CharField(max_length=500)),
                ('coor_last_name', models.CharField(max_length=500)),
                ('coor_middle_name', models.CharField(max_length=500)),
                ('idCoor', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('dean_first_name', models.CharField(max_length=500)),
                ('dean_last_name', models.CharField(max_length=500)),
                ('dean_middle_name', models.CharField(max_length=500)),
                ('idDe', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_first_name', models.CharField(max_length=500)),
                ('faculty_last_name', models.CharField(max_length=500)),
                ('faculty_middle_name', models.CharField(max_length=500)),
                ('idFa', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_name', models.CharField(max_length=200, unique=True)),
                ('idGa', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_name', models.CharField(max_length=500, unique=True)),
                ('partner_location', models.CharField(blank=True, max_length=500, null=True)),
                ('partner_description', models.TextField(blank=True, null=True)),
                ('mou_sla', models.FileField(blank=True, null=True, upload_to='uploads/partner_cmo/')),
                ('idPa', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPicture',
            fields=[
                ('project_picture', models.ImageField(blank=True, null=True, upload_to='uploads/project/pictures/')),
                ('idPP', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('year_name', models.CharField(max_length=200, unique=True)),
                ('annual_slp_plan', models.FileField(blank=True, null=True, upload_to='uploads/schoolyear/plan/')),
                ('idSy', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('sdg_name', models.CharField(choices=[('No Poverty', 'No Poverty'), ('Zero Hunger', 'Zero Hunger'), ('Good Health and Well Being', 'Good Health and Well Being'), ('Quality Education', 'Quality Education'), ('Gender Equaility', 'Gender Equaility'), ('Clean Water and Sanitation', 'Clean Water and Sanitation'), ('Affordable and Clean Energy', 'Affordable and Clean Energy'), ('Decent Work and Economic Growth', 'Decent Work and Economic Growth'), ('Industry, Innovation, and Infrastructure', 'Industry, Innovation, and Infrastructure'), ('Reduced Inequalities', 'Reduced Inequalities'), ('Sustainable Cites and Communities', 'Sustainable Cites and Communities'), ('Responsible Consumption and Production', 'Responsible Consumption and Production'), ('Climate Action', 'Climate Action'), ('Life Below Water', 'Life Below Water'), ('Life on Land', 'Life on Land'), ('Peace, Justice and Strong Institutions', 'Peace, Justice and Strong Institutions'), ('Partnerships for the Goals', 'Partnerships for the Goals')], max_length=500)),
                ('sdg_pic', models.ImageField(blank=True, null=True, upload_to='uploads/sdg_pictures/')),
                ('idSd', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_first_name', models.CharField(max_length=500)),
                ('student_last_name', models.CharField(max_length=500)),
                ('student_middle_name', models.CharField(max_length=500)),
                ('pre_sl', models.URLField(blank=True, max_length=500, null=True)),
                ('post_sl', models.URLField(blank=True, max_length=500, null=True)),
                ('cmo', models.FileField(blank=True, null=True, upload_to='uploads/students_cmo/')),
                ('idSt', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_name', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester'), ('Intersession', 'Intersession')], max_length=50)),
                ('accomplishment_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('idSe', models.AutoField(primary_key=True, serialize=False)),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slpapp.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_detail_picture', models.ImageField(blank=True, null=True, upload_to='project/')),
                ('project_name', models.CharField(max_length=500)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing')], default='Ongoing', max_length=500, null=True)),
                ('sl', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect'), ('Research', 'Research'), ('Advocacy', 'Advocacy')], default='Direct', max_length=500, null=True)),
                ('subject_hosted', models.CharField(blank=True, max_length=500, null=True)),
                ('academic_program', models.CharField(blank=True, max_length=500)),
                ('project_output', models.FileField(blank=True, null=True, upload_to='uploads/projects/outputs/')),
                ('cmo63', models.FileField(blank=True, null=True, upload_to='uploads/projects/cmo/')),
                ('idPr', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiary', models.ManyToManyField(blank=True, to='slpapp.beneficiary')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.college')),
                ('faculty', models.ManyToManyField(blank=True, to='slpapp.faculty')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slpapp.partner')),
                ('pictures', models.ManyToManyField(blank=True, to='slpapp.projectpicture')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.schoolyear')),
                ('sdg', models.ManyToManyField(blank=True, to='slpapp.sdg')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.semester')),
                ('student', models.ManyToManyField(blank=True, to='slpapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/gallery/')),
                ('idPi', models.AutoField(primary_key=True, serialize=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.gallery')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slpapp.coordinator'),
        ),
        migrations.AddField(
            model_name='college',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slpapp.dean'),
        ),
        migrations.AddField(
            model_name='college',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slpapp.schoolyear'),
        ),
        migrations.AddField(
            model_name='college',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slpapp.semester'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_picture', models.ImageField(blank=True, null=True, upload_to='uploads/schoolyear/articles/')),
                ('article_name', models.CharField(max_length=200, unique=True)),
                ('article_description', models.TextField(blank=True, null=True)),
                ('idAr', models.AutoField(primary_key=True, serialize=False)),
                ('school_year_ar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slpapp.schoolyear')),
            ],
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('school_year', 'semester_name'), name='unique_school_year_semester_name'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('college', 'project_name'), name='unique_college_project_name'),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('semester', 'college_name'), name='unique_semester_college'),
        ),
    ]
