# Generated by Django 3.2.4 on 2023-05-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
