# Generated by Django 3.2.19 on 2023-05-12 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('articleTitle', models.CharField(max_length=500)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('complete', 'Complete')], max_length=500)),
                ('slType', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect'), ('research', 'Research'), ('advocacy', 'Advocacy')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('reportType', models.CharField(max_length=500)),
                ('reportFile', models.FileField(upload_to='uploads/reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=500)),
                ('preSL', models.URLField()),
                ('postSL', models.URLField()),
                ('cmo', models.FileField(upload_to='uploads/students_cmo/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partnerId', models.AutoField(primary_key=True, serialize=False)),
                ('partnerName', models.CharField(max_length=500)),
                ('mou', models.FileField(upload_to='uploads/partner_mous/')),
                ('partnerDesc', models.TextField()),
                ('parnerLoc', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('pcitureId', models.AutoField(primary_key=True, serialize=False)),
                ('pictures', models.FileField(upload_to='uploads/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.AutoField(primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=500)),
                ('facultyPic', models.FileField(upload_to='uploads/faculty_pics/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('benificariId', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slpapp.projects')),
            ],
        ),
    ]
